language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
script: phpunit --configuration tests/phpunit.xml --coverage-text
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de
install:
  - language-pack-de
  - composer self-update
  - composer update --prefer-dist